alpha: 0.0
batch_size: 16
batch_type: sents
beam_size: 5
gpu: -1
length_penalty: none
max_length: 100
min_length: 0
n_best: 1
random_sampling_temp: 1.0
random_sampling_topk: 1
sample_rate: 16000
seed: 2019
shard_size: 10000
verbose: 'true'